aenode:
  image:
    repository: aeternity/aeternity
    tag: v6.5.2
  type: StatefullSet
  replicaCount: 1
  podSecurityContext:
    fsGroup: 1000
  service:
    port: 3013
  resources:
    limits:
      cpu: 1.2
    requests:
      cpu: 1.1
  ingress:
    enabled: "true"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: "dev-aenode.dev.aepps.com" # has to be changed/disscused
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - "dev-aenode.dev.aepps.com"
        secretName: dev-net-aenode-cert
    tls:

  tolerations:
  - key: "public"
    operator: "Equal"
    value: "yes"
    effect: "NoSchedule"
  nodeSelector:
    public: "yes"
  nodeport: "no"
  testing:
    enabled: true
  configmaps:
    enabled: true
    maps:
      aeternity.yaml:
        data: |
          chain:
              garbage_collection:
                  enabled: true
                  history: 500
                  interval: 480
              persist: true
          fork_management:
              network_id: ae_mainnet
          http:
              external:
                  port: 3013
              internal:
                  port: 3113
          keys:
              dir: keys
              peer_password: secret
          logging:
              level: warning
          metrics:
              host: 127.0.0.1
              port: 8125
          mining:
              autostart: false
          peers:
          - aenode://pp_2gPZjuPnJnTVEbrB9Qgv7f4MdhM4Jh6PD22mB2iBA1g7FRvHTk@52.220.198.72:3015
          - aenode://pp_H4ooofyixJE6weqsgzKMKTdjZwEWb2BMSWqdFqbwZjssvtUEZ@18.217.69.24:3015
          - aenode://pp_2eu9njAqnd2s9nfSHNCHMbw96dajSATz1rgT6PokH2Lsa531Sp@3.17.15.122:3015
          - aenode://pp_21DNLkjdBuoN7EajkK3ePfRMHbyMkhcuW5rJYBQsXNPDtu3v9n@35.166.231.86:3015
          - aenode://pp_RKVZjm7UKPLGvyKWqVZN1pXN6CTCxfmYz2HkNL2xiAhLVd2ho@52.11.110.179:3015
          - aenode://pp_sGegC48UrvDA7cvvUU3GPTze9wNUnnK1P4q46mL5jAFddNrbD@13.250.144.60:3015
          - aenode://pp_2R7a7JHzfZQU5Ta7DJnFiqRr7ayCcAVakqYzJ2mvZj5k4ms5mV@3.17.15.239:3015
          - aenode://pp_8nn6ypcwkaXxJfPGq7DCpBpf9FNfmkXPvGCjJFnLzvwjhCMEH@52.26.157.37:3015
          - aenode://pp_QkNjQbJL3Ab1TVG5GesKuZTixBdXEutUtxG677mVu9D4mMNRr@13.228.202.140:3015
          - aenode://pp_7N7dkCbg39MYzQv3vCrmjVNfy6QkoVmJe3VtiZ3HRncvTWAAX@13.53.114.199:3015
          - aenode://pp_2LnQXCmGqEJymtHAeUGjgcXU7dPLBbsut9rAXDG3nb7sCQK4fN@13.53.213.137:3015
          - aenode://pp_NPrJPXfzBU8da5Ufy2o2LmyHXhLX733NPHER2Xh3cTcbK2BDD@13.53.78.163:3015
          - aenode://pp_8j1ZGNDJVH3PzHvp6fMkmWr5q7WGtGA9Wxwmarh7paZS2UsDg@47.254.179.209:3015
          - aenode://pp_Wmt5BLDUEvtdepfDy4uP25RddDDBchJE9v5m1vGgiLV9DUkVP@39.98.92.160:3015
          - aenode://pp_2SUrvyk68SSeQFvXUZhenqHVahHXJHmefMkSgyE5hD4BaXduoc@39.98.94.94:3015
          - aenode://pp_2yJFvQHRDJkyhXSojDg7cSNoXaYU6hrtttknr2sDzJyimTR8m@118.31.59.151:3015
          sync:
              max_gossip: 100
              max_inbound: 200
              max_outbound: 30
              port: 3015

      aeternity.example:
        data: |
          {"somefile":"awesome"}
