app:
  image:
    repository: aeternity/aeternity
    tag: v6.5.2
  type: StatefullSeta
  replicaCount: 3
  podSecurityContext:
    fsGroup: 1000
  service:
    port: 3013
  resources:
    limits:
      cpu: 1.2
    requests:
      cpu: 1.1
#  ingress:
#    enabled: "true"
#    hosts:
#      - host: "dev-aenode.dev.aepps.com" # has to be changed/disscused
#        paths:
#          - path: "/"
  tolerations:
  - key: "public"
    operator: "Equal"
    value: "yes"
    effect: "NoSchedule"
  nodeSelector:
    public: "yes"
  nodeport: "no"
  testing:
    enabled: true
