{{- if .Values.configmaps.enabled -}}
{{- range $key, $value := .Values.configmaps.maps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
    {{ $key }}: |
    {{ .data  | nindent 4 }}
---
{{- end }}
{{- end }}
