aenode:
  image:
    repository: aeternity/aeternity
    tag: v6.5.2
  type: StatefullSet
  replicaCount: 1
  podSecurityContext:
    fsGroup: 1000
  resources:
    limits:
      cpu: 1.2
    requests:
      cpu: 1.1
