app:
  image:
    repository: aeternity/aeternity
    tag: v6.5.2
  type: StatefullSet
  replicaCount: 1
  podSecurityContext:
    fsGroup: 1000
  ingress:
    enabled: "true"
    hosts:
      - host: "dev-hc-node.dev.aepps.com" # has to be changed/disscused
        paths:
          - path: "/"
