app:
  image:
    repository: aeternity/aeternity
    tag: v6.5.2
  type: StatefullSet
  replicaCount: 2
  podSecurityContext:
    fsGroup: 1000
  service:
    port: 3013
  ingress:
    enabled: "true"
    hosts:
      - host: "dev-hc-node.dev.aepps.com" # has to be changed/disscused
        paths:
          - path: "/"
