{{ $versions := .Values.versions }}
{{ $allVersions := append $versions (merge (dict "version" (default .Values.image.tag .Chart.AppVersion )) $) | compact | uniq }}
{{- range $key, $val := $allVersions}}
{{- if $val.version }}
---

apiVersion: v1
kind: Service
metadata:
  name: node-port
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $val.version }}
    statefulset.kubernetes.io/pod-name: dev-net-hyperchain-app-1
spec:
  externalTrafficPolicy: Cluster
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $val.version }}
    statefulset.kubernetes.io/pod-name: dev-net-hyperchain-app-1
  type: NodePort
  ports:
  - protocol: TCP
    port: 3013
    targetPort: 3013
{{- end }}
{{- end }}
